### ISSUE TITLE
Additional parameters available for Append Row(s)

### ISSUE THREAD

**Issue by christophdb** [seatable/openapi#12]
Does Append Rows (https://api.seatable.io/v4.4/reference/appendrows) support one of these parameters?

- need_convert_back
- apply_default

**Comment by r350178982** [comment]
> https://api.seatable.io/v4.4/reference/appendrows

Hi，apply_default is supported as the docs shown, and need_convert_back is no longger supported

**Comment by christophdb** [comment]
api description correct now. issue closed
