### ISSUE TITLE
`appendColumns`: Unsupported column types (?)

### ISSUE THREAD

**Issue by simonhammes** [seatable/openapi#28]
I'm using the following cURL request (against a SeaTable instance running v5.0):

```bash
curl --request POST \
     --url https://SERVER/api-gateway/api/v2/dtables/BASE_UUID/batch-append-columns/ \
     --header 'accept: application/json' \
     --header 'authorization: Bearer <TOKEN>' \
     --header 'content-type: application/json' \
     --data '
{
  "table_name": "Table1",
  "columns": [
    {
      "column_type": "formula",
      "column_data": {
        "formula": "1+1"
      },
      "column_name": "formula-column"
    }
  ]
}
'
```

The API returns HTTP 200 + `{"columns": []}` and does not insert the column. The same happens for the `link` and `link-formula` column types.

---

Are there some column types which are not supported when using the `batch-append-columns` endpoint?
If yes, then this should be documented here: https://api.seatable.io/reference/appendcolumns-1

**Comment by r350178982** [comment]
> I'm using the following cURL request (against a SeaTable instance running v5.0):
> 
> ```shell
> curl --request POST \
>      --url https://SERVER/api-gateway/api/v2/dtables/BASE_UUID/batch-append-columns/ \
>      --header 'accept: application/json' \
>      --header 'authorization: Bearer <TOKEN>' \
>      --header 'content-type: application/json' \
>      --data '
> {
>   "table_name": "Table1",
>   "columns": [
>     {
>       "column_type": "formula",
>       "column_data": {
>         "formula": "1+1"
>       },
>       "column_name": "formula-column"
>     }
>   ]
> }
> '
> ```
> 
> The API returns HTTP 200 + `{"columns": []}` and does not insert the column. The same happens for the `link` and `link-formula` column types.
> 
> Are there some column types which are not supported when using the `batch-append-columns` endpoint? If yes, then this should be documented here: https://api.seatable.io/reference/appendcolumns-1

Hi, we just check the original code of batch-append-columns API, and found that the link, formula, and link-formua type columns are not  being supported.

**Comment by simonhammes** [comment]
> Hi, we just check the original code of batch-append-columns API, and found that the link, formula, and link-formua type columns are not being supported.

Thank you for the clarification. I'll document this.
